build-sys: make clean needs to remove cron-paths.h
The file is generated at build time.  This change is needed to make
distcheck work without an error.

[...]
ERROR: files left in build directory after distclean:
./src/cron-paths.h

Signed-off-by: Sami Kerola <kerolasa@iki.fi>